#if !canImport(ObjectiveC)
import XCTest

extension OrderTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__OrderTest = [
        ("testHtmlReceiptOneDefy", testHtmlReceiptOneDefy),
        ("testHtmlReceiptOneDuraAce", testHtmlReceiptOneDuraAce),
        ("testHtmlReceiptOneElite", testHtmlReceiptOneElite),
        ("testReceiptOneDefy", testReceiptOneDefy),
        ("testReceiptOneDuraAce", testReceiptOneDuraAce),
        ("testReceiptOneElite", testReceiptOneElite),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(OrderTest.__allTests__OrderTest),
    ]
}
#endif
